spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/arts_db
spring.datasource.username=postgres
spring.datasource.password=aayush25

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql